apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: chapter3
spec:
  maxReplicas: 20
  minReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 65
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        averageValue: 1Gi
        type: AverageValue
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
