apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: chapter3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: basic-auth
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources: 
          requests:
            memory: 200Mi 
            cpu: 100m 
          limits:
            memory: 1Gi
            cpu: 250m
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: /etc/secret
