apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: disposable
  name: disposable
  namespace: rm
spec:
  containers:
  - image: nginx:1.21.1
    name: disposable
    ports:
    - containerPort: 80
    resources: {}
