apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-pvc
  namespace: chapter6
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: "custom"