apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: chapter6
spec:
  containers:
    - name: main
      image: nginx
      volumeMounts:
      - mountPath: "/var/log/nginx"
        name: logs-pvc-volume
  volumes:
    - name: logs-pvc-volume
      persistentVolumeClaim:
        claimName: logs-pvc