apiVersion: v1
kind: Pod
metadata:
  labels:
    app: stress1
  name: stress1
  namespace: chapter7
spec:
  containers:
  - image: polinux/stress:1.0.4
    name: stress
    command: ["/bin/sh"]
    args:  ["-c", "stress --vm 1 --vm-bytes $(shuf -i 20-200 -n 1)M --vm-hang 1"]
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 100m
        memory: 250Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
