apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: api-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - get
