apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: operator
  name: operator
  namespace: apps
spec:
  serviceAccountName: api-access
  containers:
  - image: nginx:1.21.1
    name: operator
    ports:
    - containerPort: 80
    resources: {}
