apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp1
  name: tmp1
  namespace: chapter7
spec:
  containers:
  - command:
    - sleep
    - "100"
    image: busybox
    name: tmp1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  serviceAccountName: test-sa
status: {}
