kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc-standard
  namespace: chapter6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
