kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  namespace: chapter6
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "" #empty for static provisioning
  resources:
    requests:
      storage: 256Mi