kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc-3
  namespace: chapter6
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard 
  dataSource:
    kind: PersistentVolumeClaim
    name: db-pvc  
  resources:
    requests:
      storage: 256Mi
