apiVersion: v1
kind: Pod
metadata:
  name: business-app
  namespace: chapter6
spec:
  volumes:
    - name: exchange-volume
      emptyDir: {}
    - name: app-volume
      persistentVolumeClaim:
        claimName: db-pvc
  containers:
    - image: nginx
      name: main
      volumeMounts:
        - mountPath: /mnt/exchange-main
          name: exchange-volume
        - mountPath: /mnt/data
          name: app-volume
    - image: busybox
      name: sidecar
      command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
      volumeMounts:
        - mountPath: /mnt/exchange-sc
          name: exchange-volume
