apiVersion: v1
kind: Pod
metadata:
  name: business-app-2
  namespace: chapter6
spec:
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: db-pvc
  containers:
    - image: nginx
      name: main
      volumeMounts:
        - mountPath: /mnt/data
          name: app-volume
