namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo #it will overwrite the initial app-label
commonAnnotations:
  oncallPager: 800-555-1212
resources:
- deployment.yaml
